# Generated by Django 4.2.3 on 2023-07-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cédula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dirección', models.CharField(max_length=100)),
                ('teléfono', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
