# Generated by Django 4.2.3 on 2023-07-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_cliente_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='documento',
        ),
    ]
