# Generated by Django 4.2.3 on 2023-07-31 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_cliente_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('número', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('cantidad', models.IntegerField()),
                ('observaciones', models.CharField(max_length=50, verbose_name='Observaciones de la venta')),
                ('iva', models.FloatField(choices=[(0.12, '12%')])),
                ('descuento', models.FloatField(choices=[(0.1, '10%'), (0.2, '20%'), (0.3, '30%')])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
